name: Actions Workflow
on:
  repository_dispatch:
  pull_request:
    type: [opened, reopened, closed, assigned]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files 1
        run: |
          pwd
          ls -a
          whoami