name: Actions Workflow

on:
  push:
    branches:
      - master
      - develop

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files 1
        run: |
          pwd
          ls -a
          whoami
