name: Container
on: push
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:14-alpine
        with: 
          entrypoint: '/bin/echo'
          args: 'Hello World'
      - name: Log node version
        uses: docker://node:14-alpine
        with: 
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:14-alpine
        with: 
          entrypoint: ./script.sh
          args: "some sring arg"
